### ISSUE TITLE
[Feature] Refactor & Implement Redesign of RB Photo Upload Experience

### ISSUE THREAD

**Issue by weerd** [DoSomething/phoenix-next#341]
_FEATURE OVERVIEW_
-------------------
#### User Story
As a developer, I want to do some cleanup on the RB uploader and make some enhancements too!

#### Additional Information (optional)
Refs https://trello.com/c/CifTBgbt/682-8-as-a-developer-i-want-to-do-some-cleanup-on-the-rb-uploader-and-make-some-enhancements-too

#### Tasks
This feature includes the following tasks:
- [x] Update the directory structure for the RB Photo Uploader to help facilitate upcoming refactors and start using current structure [#325](https://github.com/DoSomething/phoenix-next/pull/325)
- [x] Separate the User's RB Submission Gallery component from the RB Photo Uploader component to allow them to be included independently [#331](https://github.com/DoSomething/phoenix-next/pull/331)
- [x] Update the action steps to allow adding RB Photo Uploader and Submission Gallery as independent, sortable items in the list of Action Steps [#333](https://github.com/DoSomething/phoenix-next/pull/333), [#337](https://github.com/DoSomething/phoenix-next/pull/337)
- [ ] Create new `Card` component to style the unstyled RBs in the Submission Gallery.
- [ ] Update the dispatch methods and aim to pull logic out and into middleware.
- [ ] Update the RB Photo Uploader to showcase the User's submitted photo based on new designs.
- ...

**Comment by itsjoekent** [comment]
@weerd I think you did the last two items in this issue right? safe to close?

**Comment by weerd** [comment]
Nope.

**Comment by weerd** [comment]
Coming back to that sooooon.
