### ISSUE TITLE
[Feature] Posts & Gallery in Phoenix Next

### ISSUE THREAD

**Issue by weerd** [DoSomething/phoenix-next#421]
_FEATURE OVERVIEW_
-----------------------

#### User Story
As a developer, I want to update and improve the way that reportback posts are rendered and how they are presented in a gallery on Phoenix Next.

#### Additional Information
Refs https://www.pivotaltracker.com/story/show/151058515

#### Why This Matters
We want reportbacks to look both great and be consistently rendered on the mosaic and legacy templates, including when they are presented in a gallery.

#### Tasks
This feature includes the following tasks:
- [x] Create a new `PostGallery` component for outputting a gallery of posts, comparable to the `SubmissionGallery` #415.
- [x] Update the styles for the RB posts and section styling for the gallery #417 .
- [ ] More to come...

**Comment by weerd** [comment]
Closing this. A few updates have happened thanks to the switch to GraphQL, with some more work refining the design in upcoming tickets.
