### ISSUE TITLE
[Feature] Phoenix Next Slugs

### ISSUE THREAD

**Issue by weerd** [DoSomething/phoenix-next#431]
_FEATURE OVERVIEW_
-----------------------

#### User Story
As a developer, I want to avoid uniqueness constraint conflicts with the `slug` field and content type instances on Contentful when creating or closing campaigns.

#### Additional Information
Please see the [Phoenix Next Slug Strategy](https://gist.github.com/weerd/0f22588382f55b5017fa11cc17d8b493) for the full context.

#### Why This Matters
We are running into lots of conflicts with campaigns and content on Contentful based on the early decisions we made with slugs for content.

#### Tasks
- [x] Remove /pages/ from campaign subpage slugs and redirect existing ones #838 
- [x] Switching around the logic to prefer campaign slug as part of subpage slug #843 
- [x] Updating logic to exclude non-page types #850 
- [x] Updating the campaign page routing to simplify it #859 
- [x] Campaign page navigation cleanup #861
