### ISSUE TITLE
Reportback Uploader

### ISSUE THREAD

**Issue by weerd** [DoSomething/phoenix-next#46]
_FEATURE OVERVIEW_
-------------------
#### User Story
> As a user, I want to be able to reportback on Phoenix-next (hold on Cropping though) so that users can RB on Phoenix-next

#### Why This Matters
We want to allow users to easily upload their Reportbacks in the new campaign experience.

#### Tasks
- [x] Create `MediaUploader` component.
- [x] Create `ReportbackUploader` component.
- [x] Send uploaded reportback to Phoenix-Ashes.
- [x] Display submitted reportback in RB Uploader interface within submission gallery.

**Comment by weerd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(13) As a user, I want to be able to reportback on Phoenix-next (hold on Cropping though) so that users can RB on Phoenix-next](https://trello.com/c/uHyDi2RL/264-13-as-a-user-i-want-to-be-able-to-reportback-on-phoenix-next-hold-on-cropping-though-so-that-users-can-rb-on-phoenix-next)
