### ISSUE TITLE
Add Twitter Share to the Share Action

### ISSUE THREAD

**Issue by mendelB** [DoSomething/phoenix-next#695]
### User Story
As a Campaign Lead, I want the new Share Action to work with Twitter. As well as the ability to toggle a Share Action to be a Twitter or Facebook share.

#### Additional Information
Pivotal ID: [#154526005](https://www.pivotaltracker.com/story/show/154526005)

### Why This Matters
This feature will work towards enabling us to depart from the screenshot Reportback format for social share actions.

### Tasks
This feature includes the following tasks:
- [ ] Add Twitter sharing functionality to the Share Action
- [ ] Add Twitter share tracking to the Share Action so we can capture the RB automatically
- [ ] Enable toggling between Facebook and Twitter for the Share Action on Contentful
